"""added user reintegration

Revision ID: 35275d6e33ec
Revises: 0f644a946760
Create Date: 2024-10-14 21:23:56.151024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35275d6e33ec'
down_revision = '0f644a946760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_user_email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_index('ix_user_email', ['email'], unique=1)
        batch_op.drop_column('year')

    # ### end Alembic commands ###
