"""init

Revision ID: 37da6e7d138f
Revises: 
Create Date: 2025-06-04 21:23:51.789129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da6e7d138f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement'))
    )
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('file_url', sa.String(length=100), nullable=True),
    sa.Column('key_stage', sa.String(length=3), nullable=False),
    sa.Column('first_correct_submission', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('maths_class', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('key_stage', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_key_stage'), ['key_stage'], unique=False)

    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('named_creator', sa.String(length=100), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_article_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    op.create_table('challenge_answer_box',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('box_label', sa.String(length=100), nullable=False),
    sa.Column('correct_answer', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_challenge_answer_box_challenge_id_challenge')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_answer_box'))
    )
    op.create_table('leaderboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('key_stage', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leaderboard_entry_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_entry'))
    )
    with op.batch_alter_table('leaderboard_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_entry_key_stage'), ['key_stage'], unique=False)

    op.create_table('answer_submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('answer_box_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_box_id'], ['challenge_answer_box.id'], name=op.f('fk_answer_submission_answer_box_id_challenge_answer_box')),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_answer_submission_challenge_id_challenge')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_answer_submission_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_submission'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_submission')
    with op.batch_alter_table('leaderboard_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_entry_key_stage'))

    op.drop_table('leaderboard_entry')
    op.drop_table('challenge_answer_box')
    op.drop_table('article')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_key_stage'))

    op.drop_table('users')
    op.drop_table('challenge')
    op.drop_table('announcement')
    # ### end Alembic commands ###
