"""Add is_mathematical field to answer boxes for math engine support

Revision ID: 4cf4c658b81f
Revises: 1ac265997595
Create Date: 2025-09-06 23:44:13.516549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf4c658b81f'
down_revision = '1ac265997595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_answer_box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mathematical', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('summer_challenge_answer_box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mathematical', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summer_challenge_answer_box', schema=None) as batch_op:
        batch_op.drop_column('is_mathematical')

    with op.batch_alter_table('challenge_answer_box', schema=None) as batch_op:
        batch_op.drop_column('is_mathematical')

    # ### end Alembic commands ###
