"""key stage and submissions system

Revision ID: 520dfd204e6b
Revises: 723bca2fdb66
Create Date: 2024-11-24 16:57:04.543707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520dfd204e6b'
down_revision = '723bca2fdb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_stage', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('key_stage')

    # ### end Alembic commands ###
