"""first_correct_submission

Revision ID: 723bca2fdb66
Revises: d2f96d7bdb11
Create Date: 2024-11-24 16:25:48.096323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723bca2fdb66'
down_revision = 'd2f96d7bdb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_correct_submission', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('first_correct_submission')

    # ### end Alembic commands ###
