"""true

Revision ID: 9bc81c640ad6
Revises: e0e3d3214c0a
Create Date: 2024-10-22 22:52:23.800856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc81c640ad6'
down_revision = 'e0e3d3214c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_submission', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
