"""named creator

Revision ID: b0ac24c0fbd7
Revises: a07a48d62d1a
Create Date: 2024-10-09 22:58:17.111457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ac24c0fbd7'
down_revision = 'a07a48d62d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('named_creator', sa.String(length=100), nullable=True))
    op.drop_column('article', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.TEXT(), nullable=True))
    op.drop_column('article', 'named_creator')
    # ### end Alembic commands ###
