"""remove is mathematical field

Revision ID: b68ba5992afc
Revises: 4cf4c658b81f
Create Date: 2025-09-07 00:10:36.807190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68ba5992afc'
down_revision = '4cf4c658b81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_answer_box', schema=None) as batch_op:
        batch_op.drop_column('is_mathematical')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_answer_box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mathematical', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
