"""init

Revision ID: d39961a2efa5
Revises: 
Create Date: 2025-07-20 13:18:31.799247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39961a2efa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement'))
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_date_posted'), ['date_posted'], unique=False)

    op.create_table('challenge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('file_url', sa.String(length=100), nullable=True),
    sa.Column('key_stage', sa.String(length=3), nullable=False),
    sa.Column('first_correct_submission', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge'))
    )
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_key_stage'), ['key_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_title'), ['title'], unique=False)

    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email_domain', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school'))
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_name'), ['name'], unique=True)

    op.create_table('summer_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('file_url', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summer_challenge'))
    )
    with op.batch_alter_table('summer_challenge', schema=None) as batch_op:
        batch_op.create_index('ix_summer_challenge_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_challenge_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_challenge_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_challenge_title'), ['title'], unique=False)

    op.create_table('challenge_answer_box',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('box_label', sa.String(length=100), nullable=False),
    sa.Column('correct_answer', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_challenge_answer_box_challenge_id_challenge')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_answer_box'))
    )
    with op.batch_alter_table('challenge_answer_box', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_answer_box_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index('ix_challenge_answer_box_challenge_order', ['challenge_id', 'order'], unique=False)

    op.create_table('summer_challenge_answer_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('box_label', sa.String(length=100), nullable=False),
    sa.Column('correct_answer', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['summer_challenge.id'], name=op.f('fk_summer_challenge_answer_box_challenge_id_summer_challenge')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summer_challenge_answer_box'))
    )
    with op.batch_alter_table('summer_challenge_answer_box', schema=None) as batch_op:
        batch_op.create_index('ix_summer_answer_box_challenge_order', ['challenge_id', 'order'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_challenge_answer_box_challenge_id'), ['challenge_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('maths_class', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('key_stage', sa.String(length=3), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('is_competition_participant', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_users_school_id_school')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_key_stage'), ['key_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)

    op.create_table('answer_submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('answer_box_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_box_id'], ['challenge_answer_box.id'], name=op.f('fk_answer_submission_answer_box_id_challenge_answer_box')),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_answer_submission_challenge_id_challenge')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_answer_submission_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_submission'))
    )
    with op.batch_alter_table('answer_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_submission_answer_box_id'), ['answer_box_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_submission_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index('ix_answer_submission_challenge_submitted', ['challenge_id', 'submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_submission_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index('ix_answer_submission_user_challenge', ['user_id', 'challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_submission_user_id'), ['user_id'], unique=False)

    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('named_creator', sa.String(length=100), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_article_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_user_id'), ['user_id'], unique=False)

    op.create_table('leaderboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('key_stage', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leaderboard_entry_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_entry'))
    )
    with op.batch_alter_table('leaderboard_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_entry_key_stage'), ['key_stage'], unique=False)
        batch_op.create_index('ix_leaderboard_entry_key_stage_score', ['key_stage', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_entry_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_entry_user_id'), ['user_id'], unique=False)

    op.create_table('summer_leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_summer_leaderboard_school_id_school')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_summer_leaderboard_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summer_leaderboard'))
    )
    with op.batch_alter_table('summer_leaderboard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summer_leaderboard_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_leaderboard_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_summer_leaderboard_school_score', ['school_id', 'score'], unique=False)
        batch_op.create_index('ix_summer_leaderboard_score', ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_leaderboard_user_id'), ['user_id'], unique=False)

    op.create_table('summer_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('answer_box_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_box_id'], ['summer_challenge_answer_box.id'], name=op.f('fk_summer_submission_answer_box_id_summer_challenge_answer_box')),
    sa.ForeignKeyConstraint(['challenge_id'], ['summer_challenge.id'], name=op.f('fk_summer_submission_challenge_id_summer_challenge')),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_summer_submission_school_id_school')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_summer_submission_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summer_submission'))
    )
    with op.batch_alter_table('summer_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summer_submission_answer_box_id'), ['answer_box_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_submission_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_submission_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_summer_submission_school_points', ['school_id', 'points_awarded'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_submission_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index('ix_summer_submission_user_challenge', ['user_id', 'challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_summer_submission_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summer_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summer_submission_user_id'))
        batch_op.drop_index('ix_summer_submission_user_challenge')
        batch_op.drop_index(batch_op.f('ix_summer_submission_submitted_at'))
        batch_op.drop_index('ix_summer_submission_school_points')
        batch_op.drop_index(batch_op.f('ix_summer_submission_school_id'))
        batch_op.drop_index(batch_op.f('ix_summer_submission_challenge_id'))
        batch_op.drop_index(batch_op.f('ix_summer_submission_answer_box_id'))

    op.drop_table('summer_submission')
    with op.batch_alter_table('summer_leaderboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summer_leaderboard_user_id'))
        batch_op.drop_index('ix_summer_leaderboard_score')
        batch_op.drop_index('ix_summer_leaderboard_school_score')
        batch_op.drop_index(batch_op.f('ix_summer_leaderboard_school_id'))
        batch_op.drop_index(batch_op.f('ix_summer_leaderboard_last_updated'))

    op.drop_table('summer_leaderboard')
    with op.batch_alter_table('leaderboard_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_entry_user_id'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_entry_last_updated'))
        batch_op.drop_index('ix_leaderboard_entry_key_stage_score')
        batch_op.drop_index(batch_op.f('ix_leaderboard_entry_key_stage'))

    op.drop_table('leaderboard_entry')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_user_id'))
        batch_op.drop_index(batch_op.f('ix_article_type'))
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_index(batch_op.f('ix_article_date_posted'))

    op.drop_table('article')
    with op.batch_alter_table('answer_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_submission_user_id'))
        batch_op.drop_index('ix_answer_submission_user_challenge')
        batch_op.drop_index(batch_op.f('ix_answer_submission_submitted_at'))
        batch_op.drop_index('ix_answer_submission_challenge_submitted')
        batch_op.drop_index(batch_op.f('ix_answer_submission_challenge_id'))
        batch_op.drop_index(batch_op.f('ix_answer_submission_answer_box_id'))

    op.drop_table('answer_submission')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_key_stage'))
        batch_op.drop_index(batch_op.f('ix_users_full_name'))

    op.drop_table('users')
    with op.batch_alter_table('summer_challenge_answer_box', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summer_challenge_answer_box_challenge_id'))
        batch_op.drop_index('ix_summer_answer_box_challenge_order')

    op.drop_table('summer_challenge_answer_box')
    with op.batch_alter_table('challenge_answer_box', schema=None) as batch_op:
        batch_op.drop_index('ix_challenge_answer_box_challenge_order')
        batch_op.drop_index(batch_op.f('ix_challenge_answer_box_challenge_id'))

    op.drop_table('challenge_answer_box')
    with op.batch_alter_table('summer_challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summer_challenge_title'))
        batch_op.drop_index(batch_op.f('ix_summer_challenge_start_date'))
        batch_op.drop_index(batch_op.f('ix_summer_challenge_end_date'))
        batch_op.drop_index('ix_summer_challenge_dates')

    op.drop_table('summer_challenge')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_name'))

    op.drop_table('school')
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_title'))
        batch_op.drop_index(batch_op.f('ix_challenge_key_stage'))
        batch_op.drop_index(batch_op.f('ix_challenge_date_posted'))

    op.drop_table('challenge')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_date_posted'))

    op.drop_table('announcement')
    # ### end Alembic commands ###
