name: Docs
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Update to v3
    - uses: actions/setup-python@v4  # Update to v4
      with:
        python-version: '3.9'  # Specify Python version
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install project dependencies
        pip install sphinx sphinx-rtd-theme
    - name: Build docs
      run: |
        cd docs
        make html
    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html