name: Docs
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install sphinx sphinx-rtd-theme
    - name: Build docs
      run: |
        cd docs
        make html
